"""initial schema

Revision ID: a3637d12c61b
Revises: 
Create Date: 2026-07-17 14:54:12.267100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3637d12c61b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('naac_grade', sa.String(length=10), nullable=True),
    sa.Column('nirf_rank', sa.Integer(), nullable=True),
    sa.Column('affiliation', sa.String(length=300), nullable=True),
    sa.Column('college_type', sa.Enum('GOVERNMENT', 'PRIVATE', 'AUTONOMOUS', 'DEEMED', 'UNKNOWN', name='collegetype', native_enum=False, length=20), nullable=False),
    sa.Column('student_strength', sa.Integer(), nullable=True),
    sa.Column('discovery_source', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'city', name='uq_college_name_city')
    )
    op.create_index('ix_colleges_state', 'colleges', ['state'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.Enum('UNSUBSCRIBED', 'HARD_BOUNCE', 'COMPLAINT', 'MANUAL', name='suppressionreason', native_enum=False, length=15), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole', native_enum=False, length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('designation_raw', sa.String(length=300), nullable=True),
    sa.Column('role', sa.Enum('TPO', 'PLACEMENT_DIRECTOR', 'TRAINING_OFFICER', 'HOD', 'DEAN', 'DIRECTOR', 'PRINCIPAL', 'VICE_PRINCIPAL', 'INNOVATION_CELL_HEAD', 'ECELL_HEAD', 'INCUBATION_HEAD', 'AI_CS_DEPT_HEAD', 'OTHER', name='canonicalrole', native_enum=False, length=30), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_mx_valid', sa.Boolean(), nullable=True),
    sa.Column('phone_office', sa.String(length=30), nullable=True),
    sa.Column('phone_direct', sa.String(length=30), nullable=True),
    sa.Column('phone_mobile_public', sa.String(length=30), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'VERIFIED', 'NEEDS_MANUAL_REVIEW', 'QUEUED', 'CONTACTED', 'REPLIED_POSITIVE', 'REPLIED_NEGATIVE', 'NO_REPLY_EXHAUSTED', 'BOUNCED', 'UNSUBSCRIBED', 'MEETING_SCHEDULED', 'WON', 'LOST', name='contactstatus', native_enum=False, length=25), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='ck_contact_confidence'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'email', name='uq_contact_college_email')
    )
    op.create_index('ix_contacts_status', 'contacts', ['status'], unique=False)
    op.create_table('research_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'WEBSITE_UNAVAILABLE', 'FAILED', name='researchstatus', native_enum=False, length=25), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id')
    )
    op.create_table('contact_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('OFFICIAL_WEBSITE', 'MANDATORY_DISCLOSURE_PDF', 'GOVT_DATABASE', 'ENRICHMENT_API', 'NEWS_ARTICLE', 'CONFERENCE_PAGE', 'PUBLIC_DOCUMENT', 'MANUAL', name='sourcetype', native_enum=False, length=30), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('touch_number', sa.Integer(), nullable=False),
    sa.Column('subject_options', sa.JSON(), nullable=True),
    sa.Column('chosen_subject', sa.String(length=300), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('lint_report', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'QUEUED', 'SENT', name='draftstatus', native_enum=False, length=15), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('touch_number >= 1 AND touch_number <= 4', name='ck_draft_touch_cap'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'touch_number', name='uq_draft_contact_touch')
    )
    op.create_table('followup_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('touch_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'CANCELLED', name='followupstatus', native_enum=False, length=10), nullable=False),
    sa.Column('cancelled_reason', sa.String(length=200), nullable=True),
    sa.CheckConstraint('touch_number >= 2 AND touch_number <= 4', name='ck_followup_touch'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'touch_number', name='uq_followup_contact_touch')
    )
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'BOUNCED', name='messagestatus', native_enum=False, length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['email_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_contact', 'email_messages', ['contact_id'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('OPEN', 'CLICK', 'BOUNCE', 'REPLY', 'UNSUBSCRIBE', name='emaileventtype', native_enum=False, length=15), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_events')
    op.drop_index('ix_messages_contact', table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_table('followup_schedules')
    op.drop_table('email_drafts')
    op.drop_table('contact_sources')
    op.drop_table('research_summaries')
    op.drop_index('ix_contacts_status', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('suppression_list')
    op.drop_index('ix_colleges_state', table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
